 setwd("~/Box Sync/MPL/corals/HIRS Stylophora expt/sym phylotypes")
system("ls")
library(vegan)
library(ggplot2)
library(ggdendro)
library(colorspace)

meta<-read.csv("coralsN2.csv",header=T, row.names=1)
meta<-meta[meta$Treatment!="Enviro",]
rownames(meta)<-gsub("Z","",rownames(meta))
rownames(meta)<-gsub(" ","_",rownames(meta))

## symptyper CLADE assignments
sym<-read.table("DETAILED_counts.tsv",header=T,row.names=1) #generated by sypTyper 'clade'
sym<-sym[,order(names(sym),decreasing=F)]
names(sym)<-unlist(strsplit(names(sym),"_"))[c(T,F,F)] 
names(sym)<-unlist(strsplit(names(sym),"Clade"))[c(F,T)] 


#import sym SUBCLADE assignment counts
subCsym<-read.table("SP_treenodeCladeDist_C.tsv",header=T,row.names=1) #generated by sypTyper 'subclade, resolved, placement'
symall<-merge(sym,subCsym,by=0,all.x=T);  rownames(symall)<-symall $Row.names; symall <-symall[,-1]
symall[is.na(symall)]<-0
symall <-symall[,order(colSums(symall),decreasing=T)]
symallF<-symall[,which(colSums(symall,na.rm=T)>200)]
#remove C clade (use subtypes instead)
symallF<-symallF[,-1]
symallF <-symallF[,order(names(symallF),decreasing=F)]


# include unassigned reads as a column
other<-read.table("ALL_counts.tsv",header=T,row.names=1)
other<-other[rownames(sym),]
notplaced<-rowSums(other[,c(2,3,4)])
symallF<-merge(symallF,notplaced,by=0,all.x=T);  rownames(symallF)<-symallF $Row.names; symallF <-symallF[,-1]
names(symallF)[length(names(symallF))]<-"notplaced"
colSums(symallF,na.rm=T)

# tidy up names to match metadata
rownames(symallF)<-unlist(strsplit(rownames(symallF),"_S"))[c(T,F)]
newnames<-unlist(strsplit(rownames(symallF),"Morrow[0-9]+-",perl=T))[c(F,T)] ; rownames(symallF)<-newnames
rownames(symallF)<-gsub("-","_",rownames(symallF))
	rownames(symallF)[which(rownames(symallF) %in% rownames(meta)==F)] # all libraries match metadata
	symallF<-symallF[which(rownames(symallF) %in% rownames(meta)==T),] # all libraries match metadata

	rownames(meta)[which(rownames(meta)%in% rownames(symallF)  ==F)] 	
meta<-meta[which(rownames(meta)%in% rownames(symallF)  ==T),]
symallF<-symallF[rownames(meta),]
#absolute
cols<-c(rev(rainbow_hcl(ncol(symallF)-1)),"gray")

barplot(t(symallF),beside=F,legend.text=T,las=2,cex.names=0.3,col=cols,border=NA,xlim=c(0,ncol(t(symallF))+20),args.legend=list(x=ncol(t(symallF))+20))
title("absolute read counts, by phylotype")

symallF <-symallF[rowSums(symallF,na.rm=T)>200,]
#sqrt transformed
barplot(t(sqrt(symallF)),beside=F,legend.text=T,las=2,cex.names=0.3,col=cols,border=NA,xlim=c(0,ncol(t(symallF))+20),args.legend=list(x=ncol(t(symallF))+20))
title("read counts (sqrt), libraries >200 reads")

#relative abundance
cols<-c(rev(rainbow_hcl(ncol(symallF)-1)),"gray")

relsym<-sqrt(symallF)/rowSums(sqrt(symallF))
colSums(relsym)
barplot(t(relsym[order(meta$Depth:meta$Light),]),beside=F,legend.text=T,las=2,cex.names=0.3,col=cols,border=NA,xlim=c(0,ncol(t(relsym))+20),args.legend=list(x=ncol(t(relsym))+20))
title("Relative abundance of Symbiodinium phylotypes")

#PERMANOVA
#on original data

#on filtered data
meta1<-meta[rownames(symallF),]; #write.csv(meta1, file="subclade_meta.csv")
adonis2(symallF ~ Depth+Light, data=meta1,permutations=999)
        # Df SumOfSqs       F Pr(>F)    
# Depth     1  0.43272 10.6573  0.001 ***
# Light     1  0.03024  0.7448  0.521    
# Residual 24  0.97448                   
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
mylightpvals<-c()
mydepthpvals<-c()
for (c in 1:ncol(symallF)){
	rawlightp<-summary(aov(symallF[,c] ~meta1$Light+ meta1$Depth))[[1]][["Pr(>F)"]][[1]]
	rawpdepth<-summary(aov(symallF[,c] ~meta1$Light + meta1$Depth))[[1]][["Pr(>F)"]][[2]]
	mylightpvals <-c(mylightpvals, rawlightp);	mydepthpvals <-c(mydepthpvals, rawpdepth)

}
names(mylightpvals)<-names(symallF)
names(mydepthpvals)<-names(symallF)

mypvals<-data.frame(cbind(p.adjust(mylightpvals,method="fdr"), p.adjust(mydepthpvals,method="fdr")))
        # mylightpvals mydepthpvals
# A           0.48245910 1.657823e-02
# B           0.49535778 7.603134e-01
# C_I.0       0.80159343 1.271101e-01
# C_I.1       0.29325116 3.561479e-01
# C_I.171     0.74246462 2.940182e-07
# C_I.197     0.34843392 2.912236e-01
# C_I.310     0.96781112 1.951602e-04
# C_I.330     0.64877699 1.234426e-04
# C_I.336     0.77334304 6.781871e-03
# C_I.51      0.26414954 9.048579e-02
# C_I.52      0.08239357 5.073588e-05
# C_I.53      0.78366464 1.222762e-04
# C_I.54      0.42736683 4.440322e-01
# C_I.61      0.88611906 7.824479e-04
# D           0.86505405 9.574672e-02
# G           0.28842652 3.644016e-01
# notplaced   0.06875304 4.778061e-02


factors<-meta1$Depth

means<-aggregate(relsym, by=list(factors), FUN=mean)
rownames(means)<-means[,1]; means<-means[,-1]
barplot(t(means),beside=F,legend.text=T,las=2,cex.names=0.3,col=cols,border=NA,xlim=c(0,ncol(t(means))+5),args.legend=list(x=ncol(t(means))+5))
title("Relative abundance of Symbiodinium phylotypes, averaged by condition")


anosim(symallF, factors)

ANOSIM statistic R: 0.4079 
      Significance: 0.001 

factors<-factor(meta1$Light:meta1$Depth)
means<-aggregate(relsym, by=list(factors), FUN=mean)
rownames(means)<-means[,1]; means<-means[,-1]
barplot(t(means),beside=F,legend.text=T,las=2,cex.names=0.3,col=cols,border=NA,xlim=c(0,ncol(t(means))+5),args.legend=list(x=ncol(t(means))+5))
title("Relative abundance of Symbiodinium phylotypes, averaged by condition")



#nMDS in vegan
library(grid)

sol <- metaMDS(sqrt(symallF))

#sample loadings
vec.samp<-envfit(sol$points, sqrt(symallF), perm=1000)
vec.samp.df<-as.data.frame(vec.samp $vectors$arrows*sqrt(vec.samp $vectors$r))
vec.samp.df$samples<-rownames(vec.samp.df)

#Fit sym type variable to oridination
scrs <- as.data.frame(scores(sol, display = "sites"))
scrs <- cbind(scrs, factors)
vf <- envfit(sol, sqrt(symallF), perm = 999)
spp.scrs <- as.data.frame(scores(vf, display = "vectors"))
spp.scrs <- cbind(spp.scrs, Samples = rownames(spp.scrs))
spp.scrs <-spp.scrs [which(mydepthpvals<0.05),]

library(ggplot2)
p <- ggplot(scrs) +
  geom_point(mapping = aes(x = NMDS1, y = NMDS2, colour = factors)) +
  coord_fixed() + ## need aspect ratio of 1!
  geom_segment(data = spp.scrs,
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "grey") +
  geom_text(data = spp.scrs, aes(x = NMDS1, y = NMDS2, label = Samples), size = 3) #+
 # geom_path(data=df_ell, aes(x=NMDS1, y=NMDS2,colour= Treat), size=0.5, linetype=2)
print(p)

#Phylogenetic relationships of subclade C phylotypes in samples
library(ape)
tre<-ladderize(read.tree("subC.tre"))
str(tre)

plot(tre, show.tip.label=F,"fan",no.margin=T)
# #tiplabels(cex=0.4,frame="n")

#get names of nodes that matched sample data
nod<-unlist(strsplit(names(symallF),"_"))[c(F,T)]
nod<-nod[grep("I.",nod)]
phylotypes<-gsub("\\.","_", nod,perl=T)
nodes<-which(tre$node.label %in% phylotypes)

plot(tre, show.tip.label=F,no.margin=T)
plot(tre, show.tip.label=T,no.margin=T,cex=0.2)

nodelabels(node=nodes+length(tre$tip.label),pch=16, col=cols,cex=3)
nodelabels(tre$node.label[nodes],node=nodes+length(tre$tip.label),frame="n", col="white",cex=0.4)
text(x=0,y=0,adj=c(0,0),labels="Phylogenetic diversity of C phylotypes identified")


